use_frameworks!

platform :ios, '8.0'

target 'HIProgressView_Example' do
  pod 'HIProgressView', :path => '../'

  target 'HIProgressView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
